create table students (
	id bigint generated by default as identity,
	first_name varchar(50) not null,
	last_name varchar(50) not null,
	date_of_birth date not null,
	email varchar(254) not null,
	index_number integer not null,
	is_on_budget boolean not null,
	primary key (id)
);
	
create table projects (
	id bigint generated by default as identity,
	project_name varchar(50) not null,
	project_description varchar(255) not null,
	student_id bigint,
	primary key (id)
);